### ISSUE TITLE
ESPHome Updated Board config?

### ISSUE THREAD

**Issue by KidA001** [strid3r21/BeeMotionS3#3]
Is there updated config for the board you reference in the [example.yaml](https://github.com/strid3r21/BeeMotionS3/blob/main/Code/ESPHome/example.yaml)
```yaml
esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  framework:
    type: arduino
    version: 2.0.3
    platform_version: 5.1.1
```

I'm getting compilation errors on ESPHome 2023.11.2 when trying to use MQTT and it only seems to be specific to this board. I have an issue open with ESP Home here: https://github.com/esphome/issues/issues/5136

**Comment by KidA001** [comment]
Updating the board info to below fixed my issue:

```yaml
esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  framework:
    type: arduino
    version: 2.0.5
    platform_version: 5.2.0
```

Your example might want to be updated
